config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_food_reviews
  resources :restaurant_foods
  resources :restaurant_comments
  get 'users/show'
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/restaurant_food_reviews_controller.rb
class RestaurantFoodReviewsController < ApplicationController
  before_action :set_restaurant_food_review, only: %i[ show edit update destroy ]

  # GET /restaurant_food_reviews or /restaurant_food_reviews.json
  def index
    @restaurant_food_reviews = RestaurantFoodReview.all
  end

  # GET /restaurant_food_reviews/1 or /restaurant_food_reviews/1.json
  def show
  end

  # GET /restaurant_food_reviews/new
  def new
    @restaurant_food_review = RestaurantFoodReview.new
  end

  # GET /restaurant_food_reviews/1/edit
  def edit
  end

  # POST /restaurant_food_reviews or /restaurant_food_reviews.json
  def create
    @restaurant_food_review = RestaurantFoodReview.new(restaurant_food_review_params)
    @restaurant_food_review.user_id = current_user.id
    respond_to do |format|
      if @restaurant_food_review.save
          url = "/restaurant_foods/" + @restaurant_food_review.restaurant_food_id.to_s
        format.html { redirect_to url, notice: "Restaurant food review was successfully created." }
        format.json { render :show, status: :created, location: @restaurant_food_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant_food_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurant_food_reviews/1 or /restaurant_food_reviews/1.json
  def update
    respond_to do |format|
      if @restaurant_food_review.update(restaurant_food_review_params)
        format.html { redirect_to @restaurant_food_review, notice: "Restaurant food review was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant_food_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant_food_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant_food_reviews/1 or /restaurant_food_reviews/1.json
  def destroy
    @restaurant_food_review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_food_reviews_url, notice: "Restaurant food review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant_food_review
      @restaurant_food_review = RestaurantFoodReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_food_review_params
      params.require(:restaurant_food_review).permit(:user_id, :restaurant_food_id, :review)
    end
end

app/helpers/restaurant_food_reviews_helper.rb
module RestaurantFoodReviewsHelper
end

app/views/restaurant_food_reviews/_form.html.erb
<%= form_with(model: restaurant_food_review, local: true) do |form| %>
  <% if restaurant_food_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant_food_review.errors.count, "error") %> prohibited this restaurant_food_review from being saved:</h2>

      <ul>
        <% restaurant_food_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :restaurant_food_id %>
    <%= form.number_field :restaurant_food_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurant_food_reviews/edit.html.erb
<div class="width-form">
<h1 class="title">Editing Restaurant Food Review</h1>

<%= render 'form', restaurant_food_review: @restaurant_food_review %>

<%= link_to 'Show', @restaurant_food_review %> |
<%= link_to 'Back', restaurant_food_reviews_path %>

</div>

app/views/restaurant_food_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurant Food Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant food</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant_food_reviews.each do |restaurant_food_review| %>
      <tr>
        <td><%= restaurant_food_review.user_id %></td>
        <td><%= restaurant_food_review.restaurant_food_id %></td>
        <td><%= restaurant_food_review.review %></td>
        <td><%= link_to 'Show', restaurant_food_review %></td>
        <td><%= link_to 'Edit', edit_restaurant_food_review_path(restaurant_food_review) %></td>
        <td><%= link_to 'Destroy', restaurant_food_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant Food Review', new_restaurant_food_review_path %>

app/views/restaurant_food_reviews/new.html.erb
<h1>New Restaurant Food Review</h1>

<%= render 'form', restaurant_food_review: @restaurant_food_review %>

<%= link_to 'Back', restaurant_food_reviews_path %>

app/views/restaurant_food_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @restaurant_food_review.user_id %>
</p>

<p>
  <strong>Restaurant food:</strong>
  <%= @restaurant_food_review.restaurant_food_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @restaurant_food_review.review %>
</p>

<%= link_to 'Edit', edit_restaurant_food_review_path(@restaurant_food_review) %> |
<%= link_to 'Back', restaurant_food_reviews_path %>