config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_food_reviews
  resources :restaurant_foods
  resources :restaurant_comments
  get 'users/show'
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant_comment.rb
class RestaurantComment < ApplicationRecord
    belongs_to :user
end

app/controllers/restaurant_comments_controller.rb
class RestaurantCommentsController < ApplicationController
  before_action :set_restaurant_comment, only: %i[ show edit update destroy ]

  # GET /restaurant_comments or /restaurant_comments.json
  def index
    @restaurant_comments = RestaurantComment.all
  end

  # GET /restaurant_comments/1 or /restaurant_comments/1.json
  def show
  end

  # GET /restaurant_comments/new
  def new
    @restaurant_comment = RestaurantComment.new
  end

  # GET /restaurant_comments/1/edit
  def edit
  end

  # POST /restaurant_comments or /restaurant_comments.json
  def create
    @restaurant_comment = RestaurantComment.new(restaurant_comment_params)
    @restaurant_comment.user_id = current_user.id
    respond_to do |format|
      if @restaurant_comment.save
        url = "/restaurants/" + @restaurant_comment.restaurant_id.to_s
        format.html { redirect_to url, notice: 'Restaurant comment was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurant_comments/1 or /restaurant_comments/1.json
  def update
    respond_to do |format|
      if @restaurant_comment.update(restaurant_comment_params)
        format.html { redirect_to @restaurant_comment, notice: "Restaurant comment was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant_comments/1 or /restaurant_comments/1.json
  def destroy
    @restaurant_comment.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_comments_url, notice: "Restaurant comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant_comment
      @restaurant_comment = RestaurantComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_comment_params
      params.require(:restaurant_comment).permit(:user_id, :restaurant_id, :comment)
    end
end

app/helpers/restaurant_comments_helper.rb
module RestaurantCommentsHelper
end

app/views/restaurant_comments/_form.html.erb
<%= form_with(model: restaurant_comment, local: true) do |form| %>
  <% if restaurant_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant_comment.errors.count, "error") %> prohibited this restaurant_comment from being saved:</h2>

      <ul>
        <% restaurant_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.number_field :restaurant_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurant_comments/edit.html.erb
<h1>Editing Restaurant Comment</h1>

<%= render 'form', restaurant_comment: @restaurant_comment %>

<%= link_to 'Show', @restaurant_comment %> |
<%= link_to 'Back', restaurant_comments_path %>

app/views/restaurant_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurant Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant_comments.each do |restaurant_comment| %>
      <tr>
        <td><%= restaurant_comment.user_id %></td>
        <td><%= restaurant_comment.restaurant_id %></td>
        <td><%= restaurant_comment.comment %></td>
        <td><%= link_to 'Show', restaurant_comment %></td>
        <td><%= link_to 'Edit', edit_restaurant_comment_path(restaurant_comment) %></td>
        <td><%= link_to 'Destroy', restaurant_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant Comment', new_restaurant_comment_path %>

app/views/restaurant_comments/new.html.erb
<h1>New Restaurant Comment</h1>

<%= render 'form', restaurant_comment: @restaurant_comment %>

<%= link_to 'Back', restaurant_comments_path %>

app/views/restaurant_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @restaurant_comment.user_id %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @restaurant_comment.restaurant_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @restaurant_comment.comment %>
</p>

<%= link_to 'Edit', edit_restaurant_comment_path(@restaurant_comment) %> |
<%= link_to 'Back', restaurant_comments_path %>