config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_food_reviews
  resources :restaurant_foods
  resources :restaurant_comments
  get 'users/show'
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_one_attached :image
    has_many :restaurant_food, -> { order "created_at ASC"}
    has_many :restaurant_comment, -> { order "created_at DESC"}
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]
before_action :authenticate_user!
  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
      @restaurant_comment = RestaurantComment.new
      @restaurant_food = RestaurantFood.new
  end
  

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :description, :image, :description2)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="form-add-infomation">
   <%= form_with(model: restaurant, local: true) do |form| %>
   <% if restaurant.errors.any? %>
   <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
      <ul>
         <% restaurant.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
      </ul>
   </div>
   <% end %>
   <div class="field">
      <%= form.label :name, "レストラン名（Name）" %>
      <%= form.text_field :name, class:"input-data-restaurant" , class:"input-data-form" %>
   </div>
   <div class="field">
      <%= form.label :address, "住所（Address）" %>
      <%= form.text_field :address, class:"input-data-restaurant", class:"input-data-form"%>
   </div>
   <div class="field">
      <%= form.label :description, "説明（Description）" %>
      <%= form.text_field :description, class:"input-data-restaurant", class:"input-data-form"%>
   </div>
   <div class="field">
      <%= form.label :description2, "レビュー内容（Review Content）" %>
      <%= form.text_area :description2, class:"input-data-restaurant", class:"input-data-form"%>
   </div>
   <div class="field">
      <%= form.label :image, "映像（Image）" %>
      <%= form.file_field :image, class:"image-upload"%>
   </div>
   <div class="actions">
      <%= form.submit %>
   </div>
   <% end %>
</div>

app/views/restaurants/edit.html.erb
<div class="width-form">
<h1 class="title">Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<div class="show-list-restaurant">
   <h1 class="text-center">Restaurants</h1>
   <div class="create-restaurant-new d-flex justify-content-end">
  
      <%= link_to ' <i class="fa fa-plus-circle" aria-hidden="true"></i> New Restaurant'.html_safe, new_restaurant_path%>
   </div>
   <div class="list-restaurant row">
      <% @restaurants.each do |restaurant| %>
      <div class="col-6">
         <div class="card mb-3 mt-2">
            <div class="row">
               <div class="col-md-5">
                  <% if restaurant.image.attached? %>
                  <%= image_tag restaurant.image, class:"image-restaurant"%>
                  <% end %> 
               </div>
               <div class="col-md-7">
                  <div class="card-body">
                     <div class="name-restaurant mb-3">
                        <div class="d-flex bd-highlight">
                           <div class="w-100 bd-highlight restaurant"><%= restaurant.name %> Restaurant</div>
                           <div class="flex-shrink-1 bd-highlight"><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_restaurant_path(restaurant) %>  </div>
                        </div>
                     </div>
                     <div class="description">
                        <p class="card-text"> Title:  <%= restaurant.description %></p>
                        <p>Description: <%= restaurant.description2 %></p>
                        <p> <i class="fa fa-map-pin" aria-hidden="true"></i> Location : <%= restaurant.address %></p> 
                     </div>
                     
                     <p class="card-text btn-learn-more">
                        <small class="text-muted float-end">
                            <%= link_to 'Learn more', restaurant, class:"btn-more" %>
                        </small>
                     </p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <% end %>
   </div>
</div>

app/views/restaurants/new.html.erb
<div class="form-restaurant bg-light width-form">
    <h1 class="title">新しいレストラン</h1>

    <%= render 'form', restaurant: @restaurant %>

    <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back'.html_safe, restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<div class="details-restaurant">
   <h1 class="text-center">
      <%= @restaurant.name %> Restaurant
   </h1>
   <div class="image-restaurant">
      <% if @restaurant.image.attached? %>
      <%= image_tag @restaurant.image%>
      <% end %>    
   </div>
   <div class="infor-details">
      <div class="infor-about-restaurant mt-5 mb-5">
         <h3 class="text-center">レストランの情報</h3>
         <table class="table ">
            <tbody>
               <tr>
                  <td>レストラン名</td>
                  <td>:</td>
                  <td><%= @restaurant.name %></td>
               </tr>
               <tr>
                  <td>住所</td>
                  <td>:</td>
                  <td><%= @restaurant.address %></td>
               </tr>
               <tr>
                  <td>タイトル</td>
                  <td>:</td>
                  <td><%= @restaurant.description %></td>
               </tr>
               <tr>
                  <td>レストランの評価</td>
                  <td>:</td>
                  <td><%= @restaurant.description2 %></td>
               </tr>

               <tr>
                  <td></td>
                  <td></td>
                  <td>
                      <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_restaurant_path(@restaurant) %>  
                  </td>
               </tr>
            </tbody>
         </table>
      </div>
      <div class="list-foods">
         <h3 class="text-center">レストラン料理のリスト</h3>
         <h5 class="float-end"><%= link_to '<i class="fa fa-plus-square" aria-hidden="true"></i> 新しい料理を追加'.html_safe, new_restaurant_food_path%></h5>
         <table class="table">
            <thead>
               <tr>
                  <th scope="col">番号</th>
                  <th scope="col">料理名</th>
                  <th scope="col">説明</th>
                  <th scope="col">映像</th>
                  <th scope="col">活動</th>
               </tr>
            </thead>
            <tbody>
               <%if @restaurant.restaurant_food.length > 0 %>
               <% @restaurant.restaurant_food.each.with_index do |restaurant_food, index| %>
               <tr>
                  <td><%= index + 1 %></th>
                  <td><%= restaurant_food.name %></td>
                  <td><%= restaurant_food.description %></td>
                  <td class="image-food"><%= image_tag restaurant_food.image %></td>
                  <td>
                  <ul class="nav justify-content-center">
                  <li class="nav-item">
                  <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, restaurant_food, class:"nav-link"%>
                  </li>
                  <li class="nav-item">
                  <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_restaurant_food_path(restaurant_food), class:"nav-link" %>
                  </li>
                 
                </ul>
                  </td>
               </tr>
               <%end%>
               <%else%>
               <tr>
                  <td>まだ食べ物はありません。</td>
               </tr>
               <%end%>
            </tbody>
         </table>
      </div>
      <div class="list-comment-restaurant">
          <h3>レストランにレビュー</h3>
         <div class="user-comment">
         <%= form_with(model: @restaurant_comment, local: true) do |form| %>
            <form>
               <div class="mb-3 input-comment">
                  <%= form.text_area :comment,  placeholder:"コメントを入力してください" %>
                  <%= form.hidden_field :restaurant_id, :value => @restaurant.id %>
               </div>
               <div class="actions-comment">
                  <%= form.submit %>
               </div>
            </form>
            <% end %> 
         </div>
         <div class="show-list-comment">
            <%if @restaurant.restaurant_comment.length > 0 %>
               <% @restaurant.restaurant_comment.each do |restaurant_comment|%>
                  <div class="card mb-3">
                  <div class="row ">
                     <div class="col-md-1">
                       <div class="image-comment">
                            <%= image_tag restaurant_comment.user.avatar %>
                       </div>
                     </div>
                     <div class="col-md-5">
                        <div class="card-body p-0">
                        <h5 class="card-title"><%= restaurant_comment.user.name %></h5>
                        <p class="card-text"> <%= restaurant_comment.comment%></p>
                        
                        </div>
                     </div>
                  </div>
                  </div>
               <% end %>
            <% end %>
         </div>

         <div class="back-btn">
             <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back'.html_safe, restaurants_path %>
         </div>
      </div>
   </div>
</div>