config/routes.rb
Rails.application.routes.draw do
  resources :restaurant_food_reviews
  resources :restaurant_foods
  resources :restaurant_comments
  get 'users/show'
  root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Group6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
   
  </head>

  <body>
   <div class="container" style="background-color: #333">
        <nav class="navbar navbar-dark navbar-expand-sm">
            <%= link_to "Restaurants Review", root_path, class: "nav-link navbar-brand" %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menuItems" aria-controls="menuItems" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="menuItems">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <%= link_to "ホーム", root_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "レストラン", restaurants_path, class: "nav-link" %>
                    </li>
                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to "プロフィール" , users_show_path, class: "nav-link"%>
                        </li>
                    <li class="nav-item">
                            <%= link_to "ログアウト" , destroy_user_session_path, method: :delete, class: "nav-link"%>
                        </li>
                    <% else %>
                        <li class="nav-item">
                          <%= link_to "サインイン", new_user_session_path, class: "nav-link"%>
                        </li>
                        <li class="nav-item">
                          <%= link_to "サインアップ", new_user_registration_path, class: "nav-link"%>
                        </li>
                  <% end %>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container mt-5">
      <%= yield %>
    </div>

  </body>
</html>